config/routes.rb
Rails.application.routes.draw do
  root to: 'summoners#index'

  resources :summoners, only: [:index, :create, :show] do
    resources :matches, only: [:index, :show]
  end
end

app/models/match.rb
require './lib/riot/client'
require 'date'

class Match < ActiveRecord::Base
  VALID_MATCH_TYPES = ["NORMAL_5x5_BLIND", "RANKED_SOLO_5x5", "RANKED_PREMADE_5x5", "NORMAL_5x5_DRAFT", "RANKED_TEAM_5x5", "GROUP_FINDER_5x5"]
  belongs_to :summoner
  has_one :match_timeline
  validates_presence_of :gold_earned, :gold_spent, :match_creation, :riot_match_id, :match_duration, :queue_type, :match_mode, :kills, :deaths
  validates_inclusion_of :winner, in: [true, false]

  def import_match_history summoner
    matches = client.match_history.by_summoner_id summoner.participant_id
    import matches, summoner
  end

  def match_duration_minutes
    match_duration / 60
  end

  def timeline_data
    {creeps_per_min: match_timeline.creeps_per_min_array, gold_per_min: match_timeline.gold_per_min_array}
  end

  protected

  def client
    Client.new(ENV["RIOT_API_KEY"], "na")
  end

  def import matches, summoner
    matches.each do |match|
      match_hash = {
        match_mode: match["matchMode"],
        queue_type: match["queueType"],
        gold_earned: match["participants"][0]["stats"]["goldEarned"],
        gold_spent: match["participants"][0]["stats"]["goldSpent"],
        match_creation: DateTime.strptime("#{match["matchCreation"] / 1000}",'%s'),
        riot_match_id: match["matchId"],
        winner: match["participants"][0]["stats"]["winner"],
        match_duration: match["matchDuration"],
        kills: match["participants"][0]["stats"]["kills"],
        deaths: match["participants"][0]["stats"]["deaths"]
      }
      unless Match.where(riot_match_id: match_hash[:riot_match_id], summoner_id: summoner.id).any? || !VALID_MATCH_TYPES.include?(match["queueType"])
        m = summoner.matches.create(match_hash)
        timeline_hash = {
          first_creeps_per_min_deltas: match["participants"][0]["timeline"]["creepsPerMinDeltas"]["zeroToTen"],
          second_creeps_per_min_deltas: match["participants"][0]["timeline"]["creepsPerMinDeltas"]["tenToTwenty"],
          third_creeps_per_min_deltas: match["participants"][0]["timeline"]["creepsPerMinDeltas"]["twentyToThirty"],
          end_creeps_per_min_deltas: match["participants"][0]["timeline"]["creepsPerMinDeltas"]["thirtyToEnd"],
          first_gold_per_min_deltas: match["participants"][0]["timeline"]["goldPerMinDeltas"]["zeroToTen"],
          second_gold_per_min_deltas: match["participants"][0]["timeline"]["goldPerMinDeltas"]["tenToTwenty"],
          third_gold_per_min_deltas: match["participants"][0]["timeline"]["goldPerMinDeltas"]["twentyToThirty"],
          end_gold_per_min_deltas: match["participants"][0]["timeline"]["goldPerMinDeltas"]["thirtyToEnd"]
        }
        timeline_hash = timeline_hash.merge({
          first_cs_diff_per_min_deltas: match["participants"][0]["timeline"]["csDiffPerMinDeltas"]["zeroToTen"],
          second_cs_diff_per_min_deltas: match["participants"][0]["timeline"]["csDiffPerMinDeltas"]["tenToTwenty"],
          third_cs_diff_per_min_deltas: match["participants"][0]["timeline"]["csDiffPerMinDeltas"]["twentyToThirty"],
          end_cs_diff_per_min_deltas: match["participants"][0]["timeline"]["csDiffPerMinDeltas"]["thirtyToEnd"]
        }) if match["participants"][0]["timeline"].has_key?("csDiffPerMinDeltas")
        m.create_match_timeline(timeline_hash)
      end
    end
  end
end

app/models/match_timeline.rb
class MatchTimeline < ActiveRecord::Base
  belongs_to :match

  def creeps_per_min_array
    [first_creeps_per_min_deltas, second_creeps_per_min_deltas, third_creeps_per_min_deltas, end_creeps_per_min_deltas]
  end

  def gold_per_min_array
    [first_gold_per_min_deltas, second_gold_per_min_deltas, third_gold_per_min_deltas, end_gold_per_min_deltas]
  end
end

app/models/summoner.rb
require './lib/riot/client'

class Summoner < ActiveRecord::Base
  has_many :matches
  has_many :match_timelines, through: :matches
  validates_presence_of :name

  def find_or_create_by_name name
    api_summoner = api_lookup name
    return api_summoner if api_summoner == "Bad Request"
    summoner = Summoner.find_by_name(api_summoner["name"])
    if summoner
      summoner
    else
      summoner = Summoner.create(name: api_summoner["name"], participant_id: api_summoner["id"])
    end
  end

  def avg_gold_earned
    matches.average(:gold_earned).round(2)
  end

  def avg_gold_spent
    matches.average(:gold_spent).round(2)
  end

  def avg_match_duration
    matches.average(:match_duration).round(2)
  end

  def readable_avg_match_duration
    "#{(avg_match_duration / 60).round} minutes #{(avg_match_duration % 60).round} seconds"
  end

  def avg_gold_per_min
    (avg_gold_earned / (avg_match_duration / 60)).round(2)
  end
#/
  def gold_earned_vs_gold_spent
    matches_array = []
    matches.each do |m|
      matches_array << {creation: m.match_creation.strftime("%B %d, %Y"), gold_earned: m.gold_earned, gold_spent: m.gold_spent}
    end
    matches_array
  end

  def gold_per_min
    matches_array = []
    matches.each do |m|
      matches_array << {creation: m.match_creation.strftime("%B %d, %Y"), gold_per_min: (m.gold_earned / m.match_duration_minutes)}
    end
    matches_array
  end

  def avg_first_creeps_per_min
    match_timelines.average(:first_creeps_per_min_deltas).round(2)
  end

  def avg_second_creeps_per_min
    match_timelines.average(:second_creeps_per_min_deltas).round(2)
  end

  def avg_third_creeps_per_min
    match_timelines.average(:third_creeps_per_min_deltas).round(2)
  end

  def avg_end_creeps_per_min
    match_timelines.average(:end_creeps_per_min_deltas).round(2)
  end

  protected

  def client
    Client.new(ENV["RIOT_API_KEY"], "na")
  end

  def api_lookup name
    client.summoner.by_name name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :load_summoner
  before_action :load_match, only: [:show]
  before_filter -> { gon.clear }

  def index
    Match.new.import_match_history @summoner
    gon.gold_earned_vs_gold_spent = @summoner.gold_earned_vs_gold_spent
    gon.gold_per_min = @summoner.gold_per_min
  end

  def show
    gon.timeline_data = @match.timeline_data
  end

  protected

  def load_match
    @match = Match.find(params[:id])
  end

  def load_summoner
    @summoner = Summoner.find(params[:summoner_id])
  end
end

app/controllers/summoners_controller.rb
class SummonersController < ApplicationController
  def index
    @summoner = Summoner.new
  end

  def create
    @summoner = Summoner.new.find_or_create_by_name(summoner_params["name"])
    if @summoner == "Bad Request"
      flash[:alert] = "That summoner name could not be found!"
      redirect_to root_path
    else
      redirect_to summoner_matches_path(@summoner)
    end
  end

  protected

  def summoner_params
    params.require(:summoner).permit(:name)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/home/index.html.slim
.container
  .row
    .col-md-1
    .col-md-10
      h1 Welcome to LoLGoldTracker!
      = form_for @summoner do |f|
        = f.input :name
        = f.submit

      / form[id="summoner"]
      /   .form-group
      /     p Enter your summoner name
      /     input[id="name" type="text" name="name" placeholder="Summoner Name"]
      /   button.btn.btn-default[type="submit"] Track
    .col-md-1

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'LoLGoldTracker', root_path, class: 'navbar-brand', id: "logo"

    .collapse.navbar-collapse
      form.navbar-form.navbar-left[id="summoner" action="/summoners"  method="POST"]
        = hidden_field_tag :authenticity_token, form_authenticity_token
        input.form-control.col-lg-8[type="text" placeholder="Search" name="summoner[name]"]

      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'LoLGoldTracker'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Lolgoldtracker'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'

    .row
      .col-md-2
      .col-md-8
        == yield

      .col-md-2

app/views/matches/index.html.slim
.page-header
  h1 Gold Data for #{@summoner.name}
.panel.panel-primary
  .panel-heading
    h3.panel-title At a Glance
  .panel-body
    h3.page-header Games Tracked: #{@summoner.matches.count}
    .row
      .col-md-3
        h4 Average gold earned: #{@summoner.avg_gold_earned}
      .col-md-3
        h4 Average gold spent: #{@summoner.avg_gold_spent}
      .col-md-3
        h4 Average match duration: #{@summoner.readable_avg_match_duration}
      .col-md-3
        h4 Average gold per min: #{@summoner.avg_gold_per_min}
    .row
      .col-md-3
        h4 Average creeps per first ten minutes: #{@summoner.avg_first_creeps_per_min}
      .col-md-3
        h4 Average creeps per second ten minutes: #{@summoner.avg_second_creeps_per_min}
      .col-md-3
        h4 Average creeps per third ten minutes: #{@summoner.avg_third_creeps_per_min}
      .col-md-3
        h4 Average creeps per minute after thirty minutes: #{@summoner.avg_end_creeps_per_min}
    h3.page-header Gold Earned vs Gold Spent
    .chart-box[id="goldEarnedvsGoldSpent"]
    h3.page-header Gold Per Minute
    .chart-box[id="goldPerMin"]
.panel.panel-primary
  .panel-heading
    h3.panel-title Match History
  .panel-body
    .list-group
      - @summoner.matches.each do |match|
        == link_to "#{match.winner ? "Win" : "Loss"} on #{match.match_creation.strftime("%B %d, %Y")}, with #{match.kills} kills and #{match.deaths} deaths", summoner_match_path(@summoner, match), class: "list-group-item"
== include_gon
== javascript_include_tag "matches-index"

app/views/matches/show.html.slim
.page-header
  h1 Match Data for #{link_to @summoner.name, summoner_matches_path(@summoner)} on #{@match.match_creation}
.panel.panel-primary
  .panel-heading
    h3.panel-title Stats
  .panel-body
    h3.page-header #{@match.winner ? "Win" : "Loss"}
    .row
      .col-md-3
        h4 Kills: #{@match.kills}
      .col-md-3
        h4 Deaths: #{@match.deaths}
      .col-md-3
        h4 Gold earned: #{@match.gold_earned}
      .col-md-3
        h4 Gold spent: #{@match.gold_spent}
    .row
      .col-md-3
        h4 Match duration: #{@match.match_duration_minutes.round}
    h3.page-header Creeps per minute
    .chart-box[id="creepsPerMin"]
    h3.page-header Gold per minute
    .chart-box[id="goldPerMin"]
== include_gon
== javascript_include_tag "matches-show"

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/summoners/create.html.slim
p Summoner : #{@summoner.name} #{@summoner.participant_id}

app/views/summoners/index.html.slim
.container
  .row
    .col-md-1
    .col-md-10
      h1 Welcome to LoLGoldTracker!
    .col-md-1

app/views/visitors/index.html.erb
<h3>Welcome</h3>